# application_settings.yml
# ========================
# This file is used to setup an application wide hash that can
# easily enable or disable specific feature sets. Any settings declared
# in this YAML file should be directly available in the ApplicationSettings class.

all:
  current_year: 2018

development:
  current_year: 2018

production:

test:
